
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: WARNING
 #LOGFILE: ./gpio2mqtt.log
 LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 1.0

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 CONSUMER: OPENHAB
 SUBSCRIBE: /GPIO1/
 PUBLISH: /OPENHAB
 CONFIG: /GPIO1/CONFIG/

#DEVICES is a fixed value
DEVICES:

 RASP:
  SYSTEM: RASPBERRY_B1
  TYPE: RASPBERRY
  UPDATE: 1.0
  #NAME: DEVICE02

  IO-17:
 #  NAME: GPIO100
   HWID: 17
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   #UPDATE Inteval
   INITIAL: ON

 I2C_x26:
  SYSTEM: RASPBERRY_B1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  UPDATE: 1.0
  #NAME: DEVICE02

  IO-01:
 #  NAME: GPIO100
   HWID: 1
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 60

  IO-02:
 #  NAME: GPIO100
   HWID: 2
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 60

  IO-09:
 #  NAME: GPIO100
   HWID: 9
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   #UPDATE Inteval
   INITIAL: ON

  LCD-01:
    MODE: LCD
    PIN_RS: 16
    PIN_E: 15
    PIN_D: [14,13,12,11]

  S0-01:
    MODE: S0
    HWID: 4
    FACTOR: 2000

