
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: WARNING
 #LOGFILE: ./gpio2mqtt.log
 LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 0.01

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 SUBSCRIBE: /GPIO_1/#
 PUBLISH: /OPENHAB
 CONFIG: /GPIO_1/CONFIG

#DEVICES is a fixed value
DEVICES:

 MCP23017_2:
  SYSTEM: RASPBERRY_B1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  UPDATE: 1
  #NAME: DEVICE02

  Port1:
 #  NAME: GPIO100
   HWID: 1
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 60

  Port2:
 #  NAME: GPIO100
   HWID: 2
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 60

  Port9:
 #  NAME: GPIO100
   HWID: 9
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   #UPDATE Inteval
   INITIAL: ON

