
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: INFO
 LOGFILE: ./gpio2mqtt.log
 #LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 0.01

BROKER:
 MQTT_HOST: localhost
 MQTT_PORT: 1883
 #MQTT Subscriber Channel
 MQTT_SUB_CH: /RASPBERRY01
 MQTT_PUB_CH: /OPENHAB

DEVICES:
 Device1:
  RASPBERRY_REV: 1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  NAME: DEVICE01

  Port0:
   NAME: GPIO100
   HWID: 0
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-IN

  Port1:
   NAME: GPIO101
   HWID: 1
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-IN

  Device3:
   RASPBERRY_REV: 1
   TYPE: RASPBERRY
   NAME: DEVICE02

  Port24:
   NAME: PWM324
   HWID: 24
   MODE: PWM

