
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: INFO
 LOGFILE: ./gpio2mqtt.log
 #LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 0.01

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 SUBSCRIBE: /SYS
 PUBLISH: /OPENHAB
 CONFIG: /CONFIG

DEVICES:
 DEVICE1:
  RASPBERRY_REV: 1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  UPDATE: 1.0
  #NAME: DEVICE01
  Port0:
   NAME: GPIO100
   HWID: 0
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
  Port1:
   NAME: GPIO101
   HWID: 1
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT

 DEVICE3:
   RASPBERRY_REV: RASPBERRY_B1
   I2C_ADDRESS: 0x31
   TYPE: MCP23017
   UPDATE: 1.5
  # NAME: DEVICE02
   Port24:
    NAME: PWM324
    HWID: 24
    MODE: BINARY-OUT

