
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: INFO
 LOGFILE: ./gpio2mqtt.log
 #LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 0.01

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 SUBSCRIBE: /TEST, /OPEN
 PUBLISH: /OPENHAB


DEVICES:
 DEVICE1:
  RASPBERRY_REV: 1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  UPDATE: 5.0
  #NAME: DEVICE01
  Port0:
   NAME: GPIO100
   HWID: 0
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-IN

