
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: WARNING
 #LOGFILE: ./gpio2mqtt.log
 LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 1.0

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 CONSUMER: OPENHAB
 SUBSCRIBE: /GPIO2/
 PUBLISH: /OPENHAB
 CONFIG: /GPIO2/CONFIG/

#DEVICES is a fixed value
DEVICES:

 RASP:
  SYSTEM: RASPBERRY_B1
  TYPE: RASPBERRY
  UPDATE: 1.0
  #NAME: DEVICE02

  PWM-01:
   MODE: PWM
   HWID: 17

  IO-17:
 #  NAME: GPIO100
   HWID: 17
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   #UPDATE Inteval
   INITIAL: ON

 I2C_x20:
  SYSTEM: RASPBERRY_B1
  I2C_ADDRESS: 0x20
  TYPE: MCP23017
  UPDATE: 1.0
  #NAME: DEVICE02

  LCD-02:
   MODE: LCD
   PIN_RS: 0
   PIN_RW: 1
   PIN_E: 2
   PIN_D: [3,4,5,6]

  IO-07:
 #  NAME: GPIO100
   HWID: 7
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 0

