
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: WARNING
 #LOGFILE: ./gpio2mqtt.log
 LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 1.0

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 CONSUMER: OPENHAB
 SUBSCRIBE: /GPIO1/
 PUBLISH: /OPENHAB
 CONFIG: /GPIO1/CONFIG/

#DEVICES is a fixed value
DEVICES:

 RASP:
  SYSTEM: RASPBERRY_B1
  TYPE: RASPBERRY
  UPDATE: 1.0
  #NAME: DEVICE02

  LCD-01:
   MODE: LCD
   PIN_RS: 7
   PIN_E: 8
   PIN_D: [25,24,23,18]

  IO-17:
 #  NAME: GPIO100
   HWID: 17
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   #UPDATE Inteval
   INITIAL: ON

 I2C_x26:
  SYSTEM: RASPBERRY_B1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  UPDATE: 0.1
  #NAME: DEVICE02

  IO-01:
 #  NAME: GPIO100
   HWID: 0
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 60

  IO-02:
 #  NAME: GPIO100
   HWID: 1
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 60

  IO-09:
 #  NAME: GPIO100
   HWID: 9
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   INTERVAL: 60
   INITIAL: ON

  IO-10:
 #  NAME: GPIO100
   HWID: 10
   ON_VALUE: ON
   OFF_VALUE: OFF
   MODE: BINARY-OUT
   INTERVAL: 60
   INITIAL: OFF

  IO-11:
   HWID: 11
   TIMER: 10
   INITIAL: OFF
   INTERVAL: 60
   MODE: TRIGGER

  IO-12:
   HWID: 12
   MODE: PULSE
   PULSE_OFF: 5.0
   PULSE_ON: 10.1
   NOTIFY: ON

  S0-01:
    MODE: S0
    HWID: 6
    FACTOR: 2000

  S0-02:
    MODE: S0
    HWID: 7
    FACTOR: 2000