
GENERAL:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
 LOGMODE: INFO
 LOGFILE: ./gpio2mqtt.log
 #LOGFILE: /var/log/gpio2mqtt.log
 UPDATE: 0.01

BROKER:
 HOST: localhost
 PORT: 1883
 #MQTT Channels
 SUBSCRIBE: /TEST, /OPEN
 PUBLISH: /OPENHAB

#DEVICES is a fixed value
DEVICES:

 MCP23017_1:
  SYSTEM: RASPBERRY_B1
  I2C_ADDRESS: 0x26
  TYPE: MCP23017
  UPDATE: 3
  #NAME: DEVICE02
  Port4:
 #  NAME: GPIO100
   HWID: 4
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 10

 RASPBERRY_IO:
  SYSTEM: RASPBERRY_B1
  I2C_ADDRESS: 0x26
  TYPE: RASPBERRY
  UPDATE: 3
  #NAME: DEVICE02
  Port1:
 #  NAME: GPIO100
   HWID: 4
   ON_VALUE: OPEN
   OFF_VALUE: CLOSED
   MODE: BINARY-IN
   #UPDATE Inteval
   INTERVAL: 10
